services:
  - type: web
    name: twomark-backend
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    rootDir: ./
    envVars:
      - key: PORT
        value: 10000
